### ISSUE TITLE
Try different languages

### ISSUE THREAD

**Issue by tschimbr** [eonum/medcodelearn#10]
Try FR and IT and combinations of FR, IT and DE for the word2vec vectorization step.

**Comment by asittampalam** [comment]
I'm running evaluations on this and #4. Please don't shutdown mars over the weekend if possible.

**Comment by tschimbr** [comment]
Results are here: https://github.com/eonum/medcodelearn/blob/9ec96741d89d2b83d8483f04c8cce672c2c29cff/validationresults/validate_tokenizers_and_languages.pdf
