### ISSUE TITLE
Use pretrained Embeddings

### ISSUE THREAD

**Issue by tschimbr** [eonum/medcodelearn#16]
See https://github.com/fchollet/keras/issues/853

**Comment by tschimbr** [comment]
Use all tokens for pretraining. Only use codable code (sum of all vectors of its tokens) for supervised training.

**Comment by anujgupta82** [comment]
@tschimbr 

Can u elaborate what do u mean by "codable code"

**Comment by tschimbr** [comment]
This is about the application's domain: medical coding. A codable or final code in the ICD (International Classification of Diseases) is a code that has no further leaf nodes or specializations. By using only the final codes we can break down the sequence lengths that are used as inputs for the neural net without loosing too much information.
Unless you are also working with medical codings this trick does not help you much. The idea is to use domain knowledge to break down input size and the model's complexity.

**Comment by tschimbr** [comment]
See PR #19
