### ISSUE TITLE
Try different Tokenizers

### ISSUE THREAD

**Issue by tschimbr** [eonum/medcodelearn#4]
Now that we are able to validate them

**Comment by asittampalam** [comment]
Working on this. (First setting up my user account on mars for anaconda etc.)

**Comment by asittampalam** [comment]
Might be worth skimming: https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjk0a3hzNnLAhUFxRQKHRvvCgsQFggcMAA&url=https%3A%2F%2Fepb.bibl.th-koeln.de%2Ffiles%2F282%2FCarevic.pdf&usg=AFQjCNG_sDCGruV1hijuHfw4YrEhYn-00Q

**Comment by tschimbr** [comment]
I'll close this for the moment. We can further elaborate on this topic when we are able to create our own domain specific tokenizers using https://github.com/eonum/medlang
